#!/usr/bin/env bash
# Installing and configuring HAproxy load balancer
sudo apt-get update
sudo apt-get install software-properties-common -y
sudo apt-add-repository ppa:vbernat/haproxy-1.7 -y
sudo apt-get update
sudo apt-get install haproxy -y
sudo apt-get install policycoreutils -y
sudo setsebool -P haproxy_connect_any=1
sudo sed -i '22 i\\nfrontend http-frontend\n\tbind \*:80\n\tmode http\n\tdefault_backend www-backend' /etc/haproxy/haproxy.cfg
sudo sed -i '27 i\\nbackend www-backend\n\tbalance roundrobin\n\tmode http\n\tserver 19017 3.237.47.144:80 check\n\tserver 19017 18.206.92.91:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart 2>&1
